apiVersion: v1
kind: Service
metadata:
  name: python-devops-demo
  namespace: demo
  labels:
    app: python-devops-demo
spec:
  type: NodePort
  selector:
    app: python-devops-demo
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
