apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-devops-demo
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app: python-devops-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
